config/routes.rb
Rails.application.routes.draw do
  resources :wishes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "wishes#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/wish.rb
class Wish < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :set_wish, only: [:show, :edit, :update, :destroy]

  # GET /wishes
  # GET /wishes.json
  def index
    @wishes = Wish.all
  end

  # GET /wishes/1
  # GET /wishes/1.json
  def show
  end

  # GET /wishes/new
  def new
    @wish = Wish.new
  end

  # GET /wishes/1/edit
  def edit
  end

  # POST /wishes
  # POST /wishes.json
  def create
    @wish = Wish.new(wish_params)

    respond_to do |format|
      if @wish.save
        format.html { redirect_to @wish, notice: 'Wish was successfully created.' }
        format.json { render :show, status: :created, location: @wish }
      else
        format.html { render :new }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishes/1
  # PATCH/PUT /wishes/1.json
  def update
    respond_to do |format|
      if @wish.update(wish_params)
        format.html { redirect_to @wish, notice: 'Wish was successfully updated.' }
        format.json { render :show, status: :ok, location: @wish }
      else
        format.html { render :edit }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishes/1
  # DELETE /wishes/1.json
  def destroy
    @wish.destroy
    respond_to do |format|
      format.html { redirect_to wishes_url, notice: 'Wish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wish
      @wish = Wish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wish_params
      params.require(:wish).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
    <title>Happy Birthday Srinivas</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
    body {
      font: 400 15px/1.8 Lato, sans-serif;
      color: #777;
    }
    .container {
      padding: 80px 120px;
    }
    .carousel-inner img {
      -webkit-filter: grayscale(90%);
      filter: grayscale(10%); /* make all photos black and white */ 
      width: 100%; /* Set width to 100% */
      margin: auto;
  }
  .carousel-inner>.item>a>img, .carousel-inner>.item>img, .img-responsive, .thumbnail a>img, .thumbnail>img{
    height: 400px !important;
  }
  .carousel-caption h3 {
      color: #fff !important;
  }
  @media (max-width: 600px) {
  }
  footer {
    background-color: #2d2d30;
    color: #f5f5f5;
    padding: 0px;
    bottom:0;
}
footer a {
    color: #f5f5f5;
}
footer a:hover {
    color: #777;
    text-decoration: none;
}
  .navbar {
    font-family: Montserrat, sans-serif;
    margin-bottom: 0;
    background-color: #101010 !important;
    border: 0;
    font-size: 11px !important;
    letter-spacing: 4px;
    opacity: 0.9;
}
.navbar li a, .navbar .navbar-brand { 
    color: #d5d5d5 !important;
}
.navbar-nav li a:hover {
    color: #fff !important;
}
.navbar-nav li.active a {
    color: #fff !important;
    background-color: #29292c !important;
}
.navbar-default .navbar-toggle {
    border-color: transparent;
}
    </style>
</head>
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="50">

<nav class="navbar navbar-default navbar-fixed-top" style="border-color:black">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="">Wish Srinivas Kotha</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "HOME", root_path %></li>
      </ul>
    </div>
  </div>
</nav>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
       <%= image_tag("happy.jpg", alt: "Happy Birthday", size: "1200x500")%>
        <div class="carousel-caption">
          <h3>Happy Birthday</h3>
          <p>I hope your special day will bring you lots of happiness, love and fun. You deserve them a lot. Enjoy!</p>
        </div>      
      </div>

      <div class="item">
      <%= image_tag("birthday.jpg", alt: "Happy Birthday", size: "1200x500")%>
        <div class="carousel-caption">
          <h3>Happy Birthday</h3>
          <p>May this birthday be filled with lots of happy hours and also your life with many happy birthdays, that are yet to come. Happy birthday.</p>
        </div>      
      </div>
    
      <div class="item">
      <%= image_tag("birthday2.jpg", alt: "Happy Birthday", size: "1200x500")%>
        <div class="carousel-caption">
          <h3>Happy Birthday</h3>
          <p>“Let your all the dreams to be on fire and light your birthday candles with that. Have a gorgeous birthday.”</p>
        </div>      
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>
    <%= yield %>
    
  <footer class="text-center">
  <a class="up-arrow" href="#myPage" data-toggle="tooltip" title="TO TOP">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a>
  <p style="margin:0px">All rights reserved. <i><a>Nikhil Iluri</a></i></p> 
</footer>

  </body>
</html>

app/views/wishes/_form.html.erb
<head>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>

</style>
</head>
<%= form_with(model: wish, local: true) do |form| %>
  <% if wish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wish.errors.count, "error") %> prohibited this wish from being saved:</h2>

      <ul>
      <% wish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container" style="padding:80px 109px">  
    <div class="row" style="width:122%">
        <div class="col-md-4">
        Follow us on<br>
        
        <a href="https://www.youtube.com/channel/UCxOUNu8KufyOZxygYRs8wrg"><i class="fa fa-youtube-play" style="font-size:35px;color:red"></i></a>
        <a href="https://www.facebook.com/srinivas.kotha.16"><i class="fa fa-facebook-square" style="font-size:32px;color:#3b5998"></i></a>
        <a href="https://www.instagram.com/iluri_nikhil/"><i class="fa fa-instagram" style="font-size:35px;color:#fb3958"></i></a>
        <br>
        </div>
        <div class="col-md-4">
            <form>
				<div class="form-group">
        			<label for="validate-text">Create wishes on your name</label>
					<div class="input-group">
						<input type="text" class="form-control" name="wish[name]" id="wish_name" placeholder="Your name" required>
					</div>
				</div>
                <button type="submit" class="btn btn-primary" name="commit" data-disable-wth="Create Wish">Create wishes</button>
            </form>
            <br>
        </div>
    </div>
</div>
<% end %>

app/views/wishes/edit.html.erb
<h1>Editing Wish</h1>

<%= render 'form', wish: @wish %>

<%= link_to 'Show', @wish %> |
<%= link_to 'Back', wishes_path %>

app/views/wishes/index.html.erb
<center>

<%= link_to 'Create wishes', new_wish_path %></p>
</center>

app/views/wishes/new.html.erb
<%= render 'form', wish: @wish %>

app/views/wishes/show.html.erb
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
w3-container{
  background-image: url("/assets/back.JPG") !important;
}
</style>
</head>
<div class="w3-container">
<p><center>Happy birthday! I hope all your birthday wishes and dreams come true.!</center></p>
<% $count = 0%>  
<div class="w3-card-4" style="width:50%;margin-left:27%" >
  <%= image_tag("srinivas.jpg", alt: "Happy Birthday", width: "100%")%>
  <div class="w3-container w3-center">
    <p>Wishes from <b>"<%= @wish.name %>"</b></p>
  </div>
</div>
</div>
<b><p id="demo" style="text-align:center;font-size:25px"></p></b>
<center><a href="whatsapp://send?text=https://newyearwishes.herokuapp.com/wishes/<%=@wish.id%>">Share it on<span> </span><i class="fa fa-whatsapp" style="font-size:30px;color:green"></a></i></center><br>
<center><i class="fa fa-bullhorn" style="font-size:26px;color:red"></i><%= link_to ' Create wishes on your name', root_path%></center><br>
<br><center>
Follow us on<br>

<a href="https://www.youtube.com/channel/UCxOUNu8KufyOZxygYRs8wrg"><i class="fa fa-youtube-play" style="font-size:35px;color:red"></i></a>
<a href="https://www.facebook.com/srinivas.kotha.16"><i class="fa fa-facebook-square" style="font-size:32px;color:#3b5998"></i></a>
<a href="https://www.instagram.com/iluri_nikhil/"><i class="fa fa-instagram" style="font-size:35px;color:#fb3958"></i></a>
</center>